### ISSUE TITLE
No actual data in repository

### ISSUE THREAD

**Issue by antong** [mkiang/beiwe_data_sample#6]
There is no actual data committed to the repository, i.e., no CSV files. Is this the intention? The README seems to imply the idea is to supply example CSV files in the same format as Beiwe produces.

`/.gitignore` contains `*.csv` which might be the culprit.

Thanks!

**Comment by antong** [comment]
Immediately after opening the issue, I found the data under the link provided in the README: https://zenodo.org/record/1188879

Sorry for the noise :-)

**Comment by mkiang** [comment]
That's fair. I will make it clearer in the README that the data are not on here. They originally were, but as we added more data, the size became an issue.
